#!/usr/bin/env python3
"""Independent structural/semantic verifier for the section-12 closure.

This verifier does not import the analysis script.  It independently checks
the frozen roster and sources, recomputes every recorded speaker intersection,
checks all finite property-case records, and verifies the manifest hash chain.
"""

from __future__ import annotations

import csv
import hashlib
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULT = ROOT / "results" / "execution_validation"
SOURCE_ROOT = ROOT / "sources_p0_5"
CASE_SEEDS = [0, 1, 2, 3, 7, 11, 17, 23, 42, 101, 313, 997, 20260810, 20260811, 20260812, 20260813]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def git_head(path: Path) -> str:
    completed = subprocess.run(
        ["git", "-c", "safe.directory=*", "-C", str(path), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip().lower()


def main() -> int:
    checks: list[str] = []
    manifest = json.loads((RESULT / "analysis_manifest.json").read_text(encoding="utf-8"))
    assert manifest["stage"] == "P0.5 section-12 evidence-tier timing-gap closure"
    assert manifest["sample_size"] == 30
    assert manifest["property_case_seeds"] == CASE_SEEDS
    assert manifest["finite_property_test_is_general_proof"] is False
    assert manifest["inference_scope"] == "public-code candidate frame generated by the preregistered search queries; no extrapolation to all SER literature"
    assert all(value is False for value in manifest["safety"].values())
    checks.append("manifest stage, construct boundary and safety flags")

    assert sha256(ROOT / manifest["analysis_script"]) == manifest["analysis_script_sha256"]
    assert sha256(ROOT / manifest["baseline_analysis_script"]) == manifest["baseline_analysis_script_sha256"]
    assert sha256(ROOT / manifest["verifier_script"]) == manifest["verifier_script_sha256"]
    for relative, expected in manifest["output_sha256"].items():
        path = RESULT / relative
        assert path.is_file(), relative
        assert sha256(path) == expected, f"output hash mismatch: {relative}"
    checks.append("analysis/baseline script and output hash chain")

    baseline = rows(RESULT / "baseline_repository_evidence.csv")
    evidence = rows(RESULT / "repository_evidence.csv")
    equivalence = rows(RESULT / "equivalence_registry.csv")
    assert len(baseline) == len(evidence) == len(equivalence) == 30
    assert len({row["repository_id"] for row in evidence}) == 30
    assert [row["repository_id"] for row in baseline] == [row["repository_id"] for row in evidence]
    assert [row["repository_id"] for row in evidence] == [row["repository_id"] for row in equivalence]
    assert {row["draw_rank"] for row in evidence} == {
        "1", "2", "4", "5", "6", "8", "9", "10", "12", "13", "14", "15", "16", "17", "18", "19",
        "20", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34",
    }
    checks.append("30-row frozen roster and baseline lineage")

    tiers = Counter(row["evidence_tier"] for row in evidence)
    outcomes = Counter(row["split_risk_final"] for row in evidence)
    assert tiers == Counter({"tier1_execution_confirmed": 24, "tier2_static_execution_inference": 1, "tier3_unknown": 5})
    assert outcomes == Counter({"yes": 20, "no": 5, "unknown": 5})
    assert tiers == Counter(manifest["tier_counts"])
    assert outcomes == Counter(manifest["outcome_counts"])
    checks.append("final tier 24/1/5 and risk 20/5/5 counts")

    survey = {row["repository_id"]: row for row in rows(ROOT / "p0_5_random_survey.csv")}
    source_dirs: dict[int, Path] = {}
    for path in SOURCE_ROOT.iterdir():
        if path.is_dir() and path.name[:4].isdigit():
            source_dirs[int(path.name[:4])] = path

    total_property_cases = 0
    total_property_passes = 0
    for row, eq_row in zip(evidence, equivalence):
        rid = row["repository_id"]
        assert row["repository_url"] == survey[rid]["repository_url"]
        assert row["commit_sha"] == survey[rid]["commit_sha"]
        assert git_head(source_dirs[int(row["draw_rank"])]) == row["commit_sha"]
        assert eq_row["repository_id"] == rid
        assert eq_row["tier_before"] == row["evidence_tier_before_section12"]
        assert eq_row["tier_after"] == row["evidence_tier"]
        assert eq_row["split_after"] == row["split_risk_final"]
        assert eq_row["general_mathematical_proof"] == "false"
        assert row["candidate_module_imported"] == "false"

        payload_path = RESULT / row["reproduction_output"]
        payload = json.loads(payload_path.read_text(encoding="utf-8"))
        assert payload["repository_id"] == rid
        assert payload["commit_sha"] == row["commit_sha"]
        assert payload["candidate_module_imported"] is False
        assert payload["whole_repository_executed"] is False
        assert payload["general_mathematical_proof"] is False
        assert payload["split_risk_after_section12"] == row["split_risk_final"]
        assert payload["safety"] == {"network": False, "gpu": False, "candidate_module_import": False, "whole_repository": False, "training": False}

        if row["evidence_tier"] == "tier1_execution_confirmed":
            assert row["candidate_code_executed"] == "true"
            assert row["original_source_fragment_executed"] == "true"
            assert payload["original_source_fragment_executed"] is True
            assert payload["adapter_equivalence"] == row["adapter_equivalence"] == "pass_finite_cases"
            assert payload["property_case_seeds"] == CASE_SEEDS
            assert len(payload["cases"]) == int(row["property_cases"]) == 16
            assert all(case["exact_index_agreement"] is True for case in payload["cases"])
            assert [case["seed"] for case in payload["cases"]] == CASE_SEEDS
            assert sum(bool(case["exact_index_agreement"]) for case in payload["cases"]) == int(row["property_cases_passed"]) == 16
            total_property_cases += len(payload["cases"])
            total_property_passes += sum(bool(case["exact_index_agreement"]) for case in payload["cases"])
            assert payload["primary_pairs"]
            max_overlap = 0
            for pair in payload["primary_pairs"]:
                independently_recomputed = sorted(set(pair["train_speakers"]) & set(pair["test_speakers"]))
                assert independently_recomputed == pair["speaker_intersection"]
                assert len(independently_recomputed) == pair["speaker_intersection_count"]
                assert len(pair["train_speakers"]) == len(set(pair["train_speakers"]))
                assert len(pair["test_speakers"]) == len(set(pair["test_speakers"]))
                max_overlap = max(max_overlap, len(independently_recomputed))
            assert max_overlap == payload["max_speaker_intersection"] == int(row["max_speaker_intersection"])
            assert row["split_risk_final"] == ("yes" if max_overlap else "no")
        else:
            assert row["candidate_code_executed"] == "false"
            assert row["original_source_fragment_executed"] == "false"
            assert payload["original_source_fragment_executed"] is False
            assert payload["property_case_count"] == int(row["property_cases"]) == 0
            assert payload["property_cases_passed"] == int(row["property_cases_passed"]) == 0
            assert not payload["primary_pairs"]
            assert row["max_speaker_intersection"] == ""
            if row["evidence_tier"] == "tier2_static_execution_inference":
                assert rid == "P05R025" and row["split_risk_final"] == "yes"
            else:
                assert row["split_risk_final"] == "unknown"
    assert total_property_cases == total_property_passes == 384
    assert total_property_cases == manifest["tier1_property_cases_total"]
    assert total_property_passes == manifest["tier1_property_cases_passed"]
    checks.append("24 exact-fragment records, 384/384 bounded property cases and independent intersections")

    row8 = next(row for row in evidence if row["repository_id"] == "P05R008")
    assert row8["evidence_tier_before_section12"] == "tier1_execution_confirmed"
    assert row8["evidence_tier"] == "tier3_unknown"
    assert row8["split_risk_final"] == "unknown"
    assert row8["tier_gap_decision"] == "downgraded_tier1_to_unknown"
    assert "external Kaggle Train/Test" in row8["inevitability_or_limit"]
    row15 = next(row for row in evidence if row["repository_id"] == "P05R015")
    assert row15["split_risk_final"] == "no"
    assert int(row15["max_speaker_intersection"]) == 0
    checks.append("P05R008 unknown downgrade and P05R015 no verdict")

    changes = rows(RESULT / "change_registry.csv")
    assert len(changes) == 6
    assert {(row["repository_id"], row["change_type"]) for row in changes} == {
        ("P05R015", "prior_stage_outcome_correction"),
        ("P05R008", "section12_evidence_and_outcome_downgrade"),
        ("P05R014", "section12_adapter_contract_clarification"),
        ("P05R017", "section12_adapter_contract_clarification"),
        ("P05R021", "section12_adapter_contract_clarification"),
        ("P05R029", "section12_adapter_contract_clarification"),
    }
    assert {row["repository_id"] for row in changes if row["outcome_changed"] == "true"} == {"P05R008", "P05R015"}
    checks.append("six-row change registry and two outcome changes")

    inventory = rows(RESULT / "source_inventory.csv")
    assert len(inventory) == 265
    assert {row["repository_id"] for row in inventory} == set(survey)
    assert all(row["candidate_code_executed"] == "false" for row in inventory)  # historical byte-read baseline inventory
    for item in inventory:
        repo_row = next(row for row in evidence if row["repository_id"] == item["repository_id"])
        path = source_dirs[int(repo_row["draw_rank"])] / Path(item["relative_path"])
        assert path.is_file()
        assert sha256(path) == item["sha256"]
        assert path.stat().st_size == int(item["bytes"])
    checks.append("265 frozen source inventory hashes")

    synthetic = rows(RESULT / "synthetic_manifest.csv")
    assert len(synthetic) == 4444
    assert len({row["row_id"] for row in synthetic}) == len(synthetic)
    assert Counter(row["corpus"] for row in synthetic) == Counter({"RAVDESS": 1440, "CREMA-D": 2184, "IEMOCAP": 400, "EmoDB": 420})
    assert all(row["speaker_id"].startswith(row["corpus"] + ":") for row in synthetic)
    checks.append("4,444-row synthetic manifest")

    summary = rows(RESULT / "tier_summary.csv")
    lookup = {(row["dimension"], row["category"]): int(row["count"]) for row in summary}
    assert lookup == {
        ("evidence_tier", "tier1_execution_confirmed"): 24,
        ("evidence_tier", "tier2_static_execution_inference"): 1,
        ("evidence_tier", "tier3_unknown"): 5,
        ("split_risk_final", "yes"): 20,
        ("split_risk_final", "no"): 5,
        ("split_risk_final", "unknown"): 5,
    }
    checks.append("tier_summary exact reconciliation")

    verification = {
        "status": "PASS",
        "checks": checks,
        "check_count": len(checks),
        "repository_count": 30,
        "tier_counts": dict(tiers),
        "outcome_counts": dict(outcomes),
        "tier1_property_cases": total_property_cases,
        "tier1_property_cases_passed": total_property_passes,
        "changed_outcome_repositories": ["P05R008", "P05R015"],
        "finite_property_test_is_general_proof": False,
        "verifier_script": "tools/verify_p0_5_execution_validation.py",
        "verifier_script_sha256": sha256(Path(__file__).resolve()),
        "analysis_script_imported": False,
        "python_executable": sys.executable,
    }
    (RESULT / "verification.json").write_text(json.dumps(verification, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(verification, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
